account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('register', views.user_register, name='register'),
]

blog_post/urls.py
from django.urls import path
from . import views

app_name = 'blog_post'
urlpatterns = [
    path('detail/<slug>', views.blog, name='article_detail'),
    path('list', views.articles_list, name='article_list'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog_post.urls')),
    # path('', include('blog_post.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    father_name = models.CharField(max_length=25)
    national_code = models.IntegerField()
    image = models.ImageField(upload_to='profile/images', null=True, blank=True)

    def __str__(self):
        return self.user.username



class New(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title = self.title.replace(' ', '-')
        super(New, self).save(args, kwargs)

blog_post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify

# unique_for_date='pub_date'


class Category(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


# با این کد base queryset را شخصی سازی میکنیم
class CustomManager(models.Manager):
    def get_queryset(self):
        return super(CustomManager, self).get_queryset().filter(status=True)


# اضافه کردن یه سری ویژگی های دلخواه به manager
# class ArticleManager(models.Manager):
#     def counter(self):
#         return len(self.all())


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=70)
    category = models.ManyToManyField(Category)
    body = models.TextField()
    image = models.ImageField(upload_to='images/article')
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    # به جای ایدی به ما یک نوشته با معنی نشان میدهد
    slug = models.SlugField(null=True, blank=True, unique=True)
    objects = models.Manager()
    custom_manager = CustomManager()
    # pub_date = models.DateField(default=timezone.now)


    # class Meta:
    #     ordering = ('-date',)


    # با این کار به جای پر کردن slug  به صورت دستی title به صورت خودکار جایگزین slug میشود و به جای space از dash استفاده میکند
    def save(self):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self):
        return reverse('blog_post:article_detail', args=[self.slug])
        # return reverse('blog_post:article_detail', kwargs={'id': self.id})

    def __str__(self):
        return f"{self.title} - {self.body[:30]}"

home/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "input100", 'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = "input100"
        self.fields['username'].widget.attrs['placeholder'] = "Username"
        self.fields['password1'].widget.attrs['class'] = "input100"
        self.fields['password1'].widget.attrs['placeholder'] = "Enter Password"
        self.fields['password2'].widget.attrs['class'] = "input100"
        self.fields['password2'].widget.attrs['placeholder'] = "Repeat Passworrd"

account/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm




# روش یوتیوب
def user_register(request):
    if request.method == 'POST':
        # به خاطر اضافه کردن اسم و فامیلی و ایمیل در پوشه forms اسم هم تغییر می کند
        # form = UserCreationForm(request.POST)
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            # messages.success(request, ('Registration successfull'))
            return redirect('home:home')
    else:
        # form = UserCreationForm()
        form = RegisterUserForm()

    return render(request, 'account/register.html', {'form': form})

def user_login(request):
    if request.user.is_authenticated == True:
        return redirect('/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
    return render(request, 'account/account.html', {})

def user_logout(request):
    logout(request)
    return redirect('/')

blog_post/views.py
from django.shortcuts import render, get_object_or_404
from blog_post.models import Article

def blog(request, slug):
    # articles = Article.objects.get(id=pk)
    articles = get_object_or_404(Article, slug=slug)
    return render(request, 'blog/post-details.html', {'articles': articles})

def articles_list(request):
    articles = Article.objects.all()
    return render(request, 'blog/articles_list.html', {'articles': articles})

home/views.py
from django.shortcuts import render
from blog_post.models import Article

def home(request):
    # articles = Article.objects.all()
    # print(Article.objects.counter())
    # articles = Article.objects.filter(status=True)
    articles = Article.custom_manager.all()
    # recent_articles = Article.objects.all()[:3]
    # recent_articles = Article.objects.all().order_by('-date')
    return render(request, 'home_app/index.html', {'articles': articles})

blog_post/templates/blog/articles_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ article.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <span>{{ article.category.all.first }}</span>
                      <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.author.get_full_name }}</a></li>
                        <li><a href="#">{{ article.date }}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <p>{{ article.body }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                            {% endfor %}

                            <div class="col-lg-12">
                                <ul class="page-numbers">
                                    <li><a href="#">1</a></li>
                                    <li class="active"><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    {% include "includes/sidebar.html" %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

home/templates/home_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
<!-- Banner Starts Here -->
<div class="main-banner header-text">
    <div class="container-fluid">
        <div class="owl-banner owl-carousel">

            {% for article in articles %}
                <div class="item">
                    <img src="{% static 'images/banner-item-01.jpg' %}" alt="">
                    <div class="item-content">
                        <div class="main-content">
                            <div class="meta-category">
                                <span>{{ article.category.all.0 }}</span>
                            </div>
{#                            <a href="{% url 'blog_post:article_detail' article.id %}"><h4>{{ article.title }}</h4></a>#}
                            <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                            <ul class="post-info">
                                <li><a href="#">{{ article.author }}</a></li>
                                <li><a href="#">{{ article.date }}</a></li>
                                <li><a href="#">12 Comments</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
</div>
<!-- Banner Ends Here -->

<section class="call-to-action">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-content">
                    <div class="row">
                        <div class="col-lg-8">
                            <span>Stand Blog HTML5 Template</span>
                            <h4>Creative HTML Template For Bloggers!</h4>
                        </div>
                        <div class="col-lg-4">
                            <div class="main-button">
                                <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                    Now!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{% static 'images/blog-post-01.jpg' %}" alt="">
                                </div>
                                <div class="down-content">
                                    <span>Lifestyle</span>
                                    <a href="post-details.html"><h4>Best Template Website for HTML CSS</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">Admin</a></li>
                                        <li><a href="#">May 31, 2020</a></li>
                                        <li><a href="#">12 Comments</a></li>
                                    </ul>
                                    <p>Stand Blog is a free HTML CSS template for your CMS theme. You can easily adapt
                                        or customize it for any kind of CMS or website builder. You are allowed to use
                                        it for your business. You are NOT allowed to re-distribute the template ZIP file
                                        on any template collection site for the download purpose. <a rel="nofollow"
                                                                                                     href="https://templatemo.com/contact"
                                                                                                     target="_parent">Contact
                                            TemplateMo</a> for more info. Thank you.</p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">Beauty</a>,</li>
                                                    <li><a href="#">Nature</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li><a href="#">Facebook</a>,</li>
                                                    <li><a href="#"> Twitter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{% static 'images/blog-post-02.jpg' %}" alt="">
                                </div>
                                <div class="down-content">
                                    <span>Healthy</span>
                                    <a href="post-details.html"><h4>Etiam id diam vitae lorem dictum</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">Admin</a></li>
                                        <li><a href="#">May 24, 2020</a></li>
                                        <li><a href="#">36 Comments</a></li>
                                    </ul>
                                    <p>You can support us by contributing a little via PayPal. Please contact <a
                                            rel="nofollow" href="https://templatemo.com/contact" target="_parent">TemplateMo</a>
                                        via Live Chat or Email. If you have any question or feedback about this
                                        template, feel free to talk to us. Also, you may check other CSS templates such
                                        as <a rel="nofollow" href="https://templatemo.com/tag/multi-page"
                                              target="_parent">multi-page</a>, <a rel="nofollow"
                                                                                  href="https://templatemo.com/tag/resume"
                                                                                  target="_parent">resume</a>, <a
                                                rel="nofollow" href="https://templatemo.com/tag/video" target="_parent">video</a>,
                                        etc.</p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">Best Templates</a>,</li>
                                                    <li><a href="#">TemplateMo</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li><a href="#">Facebook</a>,</li>
                                                    <li><a href="#">Twitter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{% static 'images/blog-post-03.jpg' %}" alt="">
                                </div>
                                <div class="down-content">
                                    <span>Fashion</span>
                                    <a href="post-details.html"><h4>Donec tincidunt leo nec magna</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">Admin</a></li>
                                        <li><a href="#">May 14, 2020</a></li>
                                        <li><a href="#">48 Comments</a></li>
                                    </ul>
                                    <p>Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque
                                        tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue,
                                        vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra
                                        leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur
                                        nibh, in vehicula eros orci vel neque.</p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">HTML CSS</a>,</li>
                                                    <li><a href="#">Photoshop</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-6">
                                                <ul class="post-share">
                                                    <li><i class="fa fa-share-alt"></i></li>
                                                    <li><a href="#">Facebook</a>,</li>
                                                    <li><a href="#">Twitter</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="main-button">
                                <a href="{% url 'blog_post:article_list' %}">View All Posts</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                {% include "includes/sidebar.html" %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% include "includes/header_references.html" %}
</head>

<body>

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.html">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog_post:article_list' %}">All Articles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="post-details.html">Post Details</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact Us</a>
                    </li>

                    {% if request.user.is_authenticated %}
                        {% if user.profile.image %}
                            <span><img src="{{ user.profile.image.url }}" width="35px" height="35px"
                                       style="border-radius: 100%"></span>
                        {% else %}
                            <span><img src="{% static 'images/icons/index.png' %}" width="35px" height="35px"
                                       style="border-radius: 100%"></span>
                        {% endif %}

                        <li class="nav-item"><a class="nav-link" href="">{{ user.first_name }}</a>
                            <a class="nav-link" href="{% url 'account:logout' %}">logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">Register</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
</header>


{% block content %}

{% endblock %}



<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

{% include 'includes/footer_references.html' %}

</body>
</html>

templates/includes/footer_references.html
{% load static %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/includes/header_references.html
{% load static %}
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
          rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <!--